name: GitHub Actions Demo
on: [push]
jobs:
  Boris4Ever:
    runs-on: self-hosted
    steps:
      - run: > 
          echo "This is env secret: $ENV_DEMO_SECRET"
          echo "This is action secret: $DEMO_SECRET"